/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top-level mesh counts
         * @description Counts of all entity types plus the most recent pipeline run timestamp. Used by the wiki home dashboard.
         */
        get: operations["stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent pipeline runs
         * @description Most recent pipeline runs, newest first. Defaults to 10.
         */
        get: operations["list_runs_api_v1_pipeline_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entities
         * @description Paginated entity list with optional `type` and `q` (case-insensitive substring match on canonical_name).
         */
        get: operations["list_entities_endpoint_api_v1_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity detail
         * @description Entity record plus all claims where it is the subject and all relationships touching it (in either direction).
         */
        get: operations["entity_detail_api_v1_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List claims
         * @description Paginated claim list with filters: predicate, source_id, entity_id (subject), status. Ordered by extraction time, newest first.
         */
        get: operations["list_claims_endpoint_api_v1_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claim detail
         * @description Claim joined with its source and subject entity for display.
         */
        get: operations["claim_detail_api_v1_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sources with claim counts
         * @description Paginated source list. Each row includes the number of claims extracted from that source — useful for ranking and the wiki home page.
         */
        get: operations["list_sources_endpoint_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source detail
         * @description Source record plus claims extracted from it (newest first).
         */
        get: operations["source_detail_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List beliefs
         * @description Paginated belief list, ordered by most recently revised. Optional topic substring filter and currently_held boolean.
         */
        get: operations["list_beliefs_endpoint_api_v1_beliefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch belief signal summaries
         * @description hype/substance score + reproduction count for the given belief ids (or all currently-held beliefs when none are given). Powers the inline signal badges on the beliefs list without an N+1 fan-out. Registered before /{belief_id} so 'signals' isn't read as an id.
         */
        get: operations["belief_signals_batch_api_v1_beliefs_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/{belief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Belief detail with full provenance
         * @description Belief plus its supporting and contradicting claims (each joined with source and subject entity) and the full revision history. Each revision lists the claims that triggered it. This is the screenshot-worthy view: claims immutable, beliefs mutable, full provenance navigable.
         */
        get: operations["belief_detail_api_v1_beliefs__belief_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/{belief_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revisions for a belief
         * @description Append-only revision history for a single belief, joined with the claims that triggered each revision. Ordered most-recent-first.
         */
        get: operations["belief_revisions_api_v1_beliefs__belief_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skeptic/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent skeptic-triggered belief revisions
         * @description Most recent BeliefRevisions where revised_by_agent='skeptic', joined with each revision's belief and trigger claims (the counter-claims the skeptic emitted). Drives the wiki's skeptic-activity feed.
         */
        get: operations["recent_skeptic_activity_api_v1_skeptic_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personalized daily briefing
         * @description Loads the user's markdown profile from $MESH_PROFILE_PATH (default ~/.config/agent_mesh/profile.md), gathers candidate beliefs, revisions, and high-confidence claims for the requested date (default today), dispatches the Personalizer agent over A2A, and returns the ranked Briefing. Result is cached in-process by (date, profile_hash); edits to the profile invalidate that day's cache.
         */
        get: operations["get_briefing_api_v1_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operational status page
         * @description Server-rendered HTML with meta-refresh every 60s. Shows last + next runs, total row counts, LangGraph checkpoint run state (in-flight / interrupted), recent run errors, and the Langfuse 24h trace count when configured.
         */
        get: operations["status_page_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge graph nodes + edges
         * @description All entities as nodes and all relationships as edges, in the shape a client-side graph library can consume directly. ``?max_nodes`` bounds the entity count for predictable browser performance on large meshes; the most recently created entities win.
         */
        get: operations["get_graph_api_v1_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pre-aggregated graph data for the redesigned /graph view
         * @description Node + edge lists with density baked in: node ``belief_count`` drives radius, edge ``claim_count`` drives stroke width. Capped at the top 200 entities by belief count; ``total_entities`` lets the UI show a 'showing N of M' notice. Edges are only included when both endpoints survive the cap.
         */
        get: operations["get_graph_data_api_v1_graph_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pipeline schedules
         * @description Current interval + enabled state for each pipeline job.
         */
        get: operations["list_schedules_endpoint_api_v1_schedules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schedules/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a pipeline schedule
         * @description Patch the interval and/or enabled flag for a job. Persists to Postgres and signals the scheduler to apply the change without a restart. ``interval_hours`` must be one of [1, 2, 4, 6, 12, 24, 48].
         */
        patch: operations["patch_schedule_api_v1_schedules__job_id__patch"];
        trace?: never;
    };
    "/api/v1/pipelines/{job_id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger an immediate pipeline run
         * @description Starts an out-of-band run of the coordinator or skeptic sweep. Returns 409 if a run for that job is already in progress.
         */
        post: operations["trigger_pipeline_api_v1_pipelines__job_id__trigger_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduler/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live scheduler job state
         * @description Per-job next-run, last-run, and state (running / idle / disabled) from the running scheduler. Returns an empty list if the scheduler is unreachable so the Pipelines page degrades gracefully.
         */
        get: operations["scheduler_status_api_v1_scheduler_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Belief */
        Belief: {
            /** Id */
            id?: string;
            /** Topic */
            topic: string;
            /** Statement */
            statement: string;
            /** Supporting Claim Ids */
            supporting_claim_ids?: string[];
            /** Contradicting Claim Ids */
            contradicting_claim_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Last Revised At
             * Format: date-time
             */
            last_revised_at?: string;
            /**
             * Revision Count
             * @default 0
             */
            revision_count: number;
            /**
             * Is Currently Held
             * @default true
             */
            is_currently_held: boolean;
        };
        /** BeliefDetail */
        BeliefDetail: {
            belief: components["schemas"]["Belief"];
            /** Supporting Claims */
            supporting_claims: components["schemas"]["ClaimWithContext"][];
            /** Contradicting Claims */
            contradicting_claims: components["schemas"]["ClaimWithContext"][];
            /** Revisions */
            revisions: components["schemas"]["RevisionWithTriggers"][];
            signals?: components["schemas"]["BeliefSignals"] | null;
        };
        /** BeliefRevision */
        BeliefRevision: {
            /** Id */
            id?: string;
            /** Belief Id */
            belief_id: string;
            /** Previous Statement */
            previous_statement: string;
            /** New Statement */
            new_statement: string;
            /** Previous Confidence */
            previous_confidence: number;
            /** New Confidence */
            new_confidence: number;
            /** Trigger Claim Ids */
            trigger_claim_ids?: string[];
            /** Revised By Agent */
            revised_by_agent: string;
            /**
             * Revised At
             * Format: date-time
             */
            revised_at?: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * BeliefSignalSummary
         * @description Just the two signals the beliefs *list* surfaces inline per row.
         *
         *     The full BeliefSignals breakdown stays on the detail page; this keeps
         *     the list's batch lookup cheap.
         */
        BeliefSignalSummary: {
            /** Belief Id */
            belief_id: string;
            /** Hype Substance Score */
            hype_substance_score: number;
            /** Reproduction Count */
            reproduction_count: number;
        };
        /**
         * BeliefSignals
         * @description Phase 7b derived signals over a belief.
         *
         *     Pulled from the belief_hype_substance + belief_reproduction views in
         *     DuckDB; recomputed on read. Informational only — does not drive any
         *     mesh behavior in 7b.
         */
        BeliefSignals: {
            /** Source Type Diversity */
            source_type_diversity: number;
            /** Reproduction Count */
            reproduction_count: number;
            /** Skeptic Counter Claim Count */
            skeptic_counter_claim_count: number;
            /** Severe Failure Mode Count */
            severe_failure_mode_count: number;
            /** Claims Last 30D */
            claims_last_30d: number;
            /** Hype Substance Score */
            hype_substance_score: number;
        };
        /**
         * Briefing
         * @description The full daily digest returned by ``GET /briefing``.
         */
        Briefing: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Profile Excerpt
             * @default
             */
            profile_excerpt: string;
            /** Sections */
            sections?: components["schemas"]["BriefingSection"][];
        };
        /**
         * BriefingSection
         * @description A named group of ranked items (e.g. "New Beliefs").
         */
        BriefingSection: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Items */
            items?: components["schemas"]["PersonalizedItem"][];
        };
        /** Claim */
        Claim: {
            /** Id */
            id?: string;
            /** Predicate */
            predicate: string;
            /** Subject Entity Id */
            subject_entity_id: string;
            /** Object */
            object: {
                [key: string]: unknown;
            };
            /** Source Id */
            source_id: string;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at?: string;
            /** Extracted By Agent */
            extracted_by_agent: string;
            /** Raw Excerpt */
            raw_excerpt: string;
            /** @default active */
            status: components["schemas"]["ClaimStatus"];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** Superseded By Claim Id */
            superseded_by_claim_id?: string | null;
            failure_mode?: components["schemas"]["FailureMode"] | null;
        };
        /** ClaimDetail */
        ClaimDetail: {
            claim: components["schemas"]["Claim"];
            source: components["schemas"]["Source"] | null;
            subject_entity: components["schemas"]["Entity"] | null;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "active" | "superseded" | "retracted" | "disputed";
        /**
         * ClaimWithContext
         * @description Claim joined with its source and subject entity for display.
         */
        ClaimWithContext: {
            claim: components["schemas"]["Claim"];
            source: components["schemas"]["Source"] | null;
            subject_entity: components["schemas"]["Entity"] | null;
        };
        /** Entity */
        Entity: {
            /** Id */
            id?: string;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases?: string[];
            type: components["schemas"]["EntityType"];
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at?: string;
        };
        /** EntityDetail */
        EntityDetail: {
            entity: components["schemas"]["Entity"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Relationships */
            relationships: components["schemas"]["Relationship"][];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "model" | "paper" | "benchmark" | "method" | "person" | "lab" | "repo" | "concept";
        /**
         * FailureMode
         * @description Structured taxonomy of why a Skeptic-authored counter-claim weakens
         *     or contradicts the belief it targets. Non-Skeptic claims leave this null.
         *
         *     Phase 7 pre-work. Skeptic emits one of these alongside its free-text
         *     rationale so downstream analysis (DSPy training, hype/substance score)
         *     can group failures without re-parsing English.
         * @enum {string}
         */
        FailureMode: "unsupported_extrapolation" | "cherry_picked_evidence" | "methodological_flaw" | "outdated_by_newer_claim" | "contradicted_by_source" | "definitional_ambiguity" | "other";
        /**
         * GraphData
         * @description Bounded graph payload. ``total_entities`` lets the UI show a
         *     "showing N of M" notice when the node list is capped.
         */
        GraphData: {
            /** Nodes */
            nodes: components["schemas"]["GraphDataNode"][];
            /** Edges */
            edges: components["schemas"]["GraphDataEdge"][];
            /** Total Entities */
            total_entities: number;
        };
        /** GraphDataEdge */
        GraphDataEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Relationship Type */
            relationship_type: string;
            /** Claim Count */
            claim_count: number;
        };
        /** GraphDataNode */
        GraphDataNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Belief Count */
            belief_count: number;
            /** Last Claim At */
            last_claim_at?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Confidence */
            confidence: number;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Present */
            db_present: boolean;
        };
        /** Page[Belief] */
        Page_Belief_: {
            /** Items */
            items: components["schemas"]["Belief"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Claim] */
        Page_Claim_: {
            /** Items */
            items: components["schemas"]["Claim"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Entity] */
        Page_Entity_: {
            /** Items */
            items: components["schemas"]["Entity"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceWithCount] */
        Page_SourceWithCount_: {
            /** Items */
            items: components["schemas"]["SourceWithCount"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PersonalizedItem
         * @description One ranked candidate the user might care about.
         */
        PersonalizedItem: {
            /**
             * Item Type
             * @enum {string}
             */
            item_type: "belief" | "revision" | "claim";
            /** Item Id */
            item_id: string;
            /** Relevance Score */
            relevance_score: number;
            /** Rationale */
            rationale: string;
        };
        /** PipelineError */
        PipelineError: {
            /** Paper Id */
            paper_id: string;
            /** Error Type */
            error_type: string;
            /** Error Message */
            error_message: string;
        };
        /** PipelineRun */
        PipelineRun: {
            /** Id */
            id?: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Run Type
             * @default pipeline
             */
            run_type: string;
            /**
             * Triggered By
             * @default manual
             */
            triggered_by: string;
            /**
             * Papers Scouted
             * @default 0
             */
            papers_scouted: number;
            /**
             * Sources Inserted
             * @default 0
             */
            sources_inserted: number;
            /**
             * Claims Inserted
             * @default 0
             */
            claims_inserted: number;
            /**
             * Entities Created
             * @default 0
             */
            entities_created: number;
            /**
             * Beliefs Created
             * @default 0
             */
            beliefs_created: number;
            /**
             * Beliefs Revised
             * @default 0
             */
            beliefs_revised: number;
            /**
             * Avg Extraction Latency Ms
             * @default 0
             */
            avg_extraction_latency_ms: number;
            /** Errors */
            errors?: components["schemas"]["PipelineError"][];
        };
        /** Relationship */
        Relationship: {
            /** Id */
            id?: string;
            /** From Entity Id */
            from_entity_id: string;
            /** To Entity Id */
            to_entity_id: string;
            /** Type */
            type: string;
            /** Evidence Claim Ids */
            evidence_claim_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /**
         * RevisionWithTriggers
         * @description Revision joined with its trigger claims for the timeline view.
         */
        RevisionWithTriggers: {
            revision: components["schemas"]["BeliefRevision"];
            /** Trigger Claims */
            trigger_claims: components["schemas"]["Claim"][];
        };
        /**
         * Schedule
         * @description One configured pipeline schedule (a ``schedules`` row).
         */
        Schedule: {
            /** Job Id */
            job_id: string;
            /** Interval Hours */
            interval_hours: number;
            /** Enabled */
            enabled: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ScheduleUpdate
         * @description Partial update for a schedule — interval, enabled, or both.
         */
        ScheduleUpdate: {
            /** Interval Hours */
            interval_hours?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * SchedulerJobStatus
         * @description Live APScheduler state for one job.
         *
         *     ``state`` is one of ``running`` | ``idle`` | ``disabled``. ``next_run_at``
         *     is null when the job is paused (disabled) or has no future fire time.
         */
        SchedulerJobStatus: {
            /** Job Id */
            job_id: string;
            /** Next Run At */
            next_run_at?: string | null;
            /** Last Run At */
            last_run_at?: string | null;
            /** State */
            state: string;
        };
        /**
         * SkepticActivityItem
         * @description One skeptic-triggered revision joined with its belief and trigger claims.
         *
         *     Powers the wiki's "what the skeptic challenged this week" feed. Belief
         *     lets the feed link back to the entity; trigger_claims are the counter-
         *     claims the skeptic emitted that drove the revision.
         */
        SkepticActivityItem: {
            revision: components["schemas"]["BeliefRevision"];
            belief: components["schemas"]["Belief"];
            /** Trigger Claims */
            trigger_claims: components["schemas"]["Claim"][];
        };
        /** Source */
        Source: {
            /** Id */
            id?: string;
            type: components["schemas"]["SourceType"];
            /** Url */
            url: string;
            /** Author */
            author?: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /** Raw Content Hash */
            raw_content_hash: string;
            /**
             * Reliability Prior
             * @default 0.5
             */
            reliability_prior: number;
        };
        /** SourceDetail */
        SourceDetail: {
            source: components["schemas"]["Source"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "arxiv" | "hn_post" | "hn_comment" | "github" | "twitter" | "bluesky" | "reddit" | "blog" | "leaderboard" | "agent_reasoning";
        /** SourceWithCount */
        SourceWithCount: {
            source: components["schemas"]["Source"];
            /** Claim Count */
            claim_count: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Entities */
            entities: number;
            /** Claims */
            claims: number;
            /** Beliefs */
            beliefs: number;
            /** Sources */
            sources: number;
            /** Revisions */
            revisions: number;
            /** Pipeline Runs */
            pipeline_runs: number;
            /** Last Pipeline Run At */
            last_pipeline_run_at: string | null;
            /** Last Pipeline Run Id */
            last_pipeline_run_id: string | null;
        };
        /**
         * TriggerResult
         * @description Result of an immediate pipeline trigger.
         */
        TriggerResult: {
            /** Run Id */
            run_id: string;
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    list_runs_api_v1_pipeline_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_endpoint_api_v1_entities_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["EntityType"] | null;
                /** @description Substring match on canonical_name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Entity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_detail_api_v1_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_endpoint_api_v1_claims_get: {
        parameters: {
            query?: {
                predicate?: string | null;
                source_id?: string | null;
                entity_id?: string | null;
                status?: components["schemas"]["ClaimStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Claim_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_detail_api_v1_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_endpoint_api_v1_sources_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["SourceType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceWithCount_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_detail_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_beliefs_endpoint_api_v1_beliefs_get: {
        parameters: {
            query?: {
                topic?: string | null;
                currently_held?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Belief_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_signals_batch_api_v1_beliefs_signals_get: {
        parameters: {
            query?: {
                ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliefSignalSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_detail_api_v1_beliefs__belief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                belief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliefDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_revisions_api_v1_beliefs__belief_id__revisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                belief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionWithTriggers"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_skeptic_activity_api_v1_skeptic_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkepticActivityItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_briefing_api_v1_briefing_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_page_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    get_graph_api_v1_graph_get: {
        parameters: {
            query?: {
                max_nodes?: number;
                max_edges?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_data_api_v1_graph_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
        };
    };
    list_schedules_endpoint_api_v1_schedules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"][];
                };
            };
        };
    };
    patch_schedule_api_v1_schedules__job_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Schedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_pipeline_api_v1_pipelines__job_id__trigger_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scheduler_status_api_v1_scheduler_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchedulerJobStatus"][];
                };
            };
        };
    };
}
