/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top-level mesh counts
         * @description Counts of all entity types plus the most recent pipeline run timestamp. Used by the wiki home dashboard.
         */
        get: operations["stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent pipeline runs
         * @description Most recent pipeline runs, newest first. Defaults to 10.
         */
        get: operations["list_runs_api_v1_pipeline_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entities
         * @description Paginated entity list with optional `type` and `q` (case-insensitive substring match on canonical_name).
         */
        get: operations["list_entities_endpoint_api_v1_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity detail
         * @description Entity record plus all claims where it is the subject and all relationships touching it (in either direction).
         */
        get: operations["entity_detail_api_v1_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List claims
         * @description Paginated claim list with filters: predicate, source_id, entity_id (subject), status. Ordered by extraction time, newest first.
         */
        get: operations["list_claims_endpoint_api_v1_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claim detail
         * @description Claim joined with its source and subject entity for display.
         */
        get: operations["claim_detail_api_v1_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sources with claim counts
         * @description Paginated source list. Each row includes the number of claims extracted from that source — useful for ranking and the wiki home page.
         */
        get: operations["list_sources_endpoint_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source detail
         * @description Source record plus claims extracted from it (newest first).
         */
        get: operations["source_detail_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List beliefs
         * @description Paginated belief list, ordered by most recently revised. Optional topic substring filter and currently_held boolean.
         */
        get: operations["list_beliefs_endpoint_api_v1_beliefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/{belief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Belief detail with full provenance
         * @description Belief plus its supporting and contradicting claims (each joined with source and subject entity) and the full revision history. Each revision lists the claims that triggered it. This is the screenshot-worthy view: claims immutable, beliefs mutable, full provenance navigable.
         */
        get: operations["belief_detail_api_v1_beliefs__belief_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/{belief_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revisions for a belief
         * @description Append-only revision history for a single belief, joined with the claims that triggered each revision. Ordered most-recent-first.
         */
        get: operations["belief_revisions_api_v1_beliefs__belief_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skeptic/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent skeptic-triggered belief revisions
         * @description Most recent BeliefRevisions where revised_by_agent='skeptic', joined with each revision's belief and trigger claims (the counter-claims the skeptic emitted). Drives the wiki's skeptic-activity feed.
         */
        get: operations["recent_skeptic_activity_api_v1_skeptic_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Belief */
        Belief: {
            /** Id */
            id?: string;
            /** Topic */
            topic: string;
            /** Statement */
            statement: string;
            /** Supporting Claim Ids */
            supporting_claim_ids?: string[];
            /** Contradicting Claim Ids */
            contradicting_claim_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Last Revised At
             * Format: date-time
             */
            last_revised_at?: string;
            /**
             * Revision Count
             * @default 0
             */
            revision_count: number;
            /**
             * Is Currently Held
             * @default true
             */
            is_currently_held: boolean;
        };
        /** BeliefDetail */
        BeliefDetail: {
            belief: components["schemas"]["Belief"];
            /** Supporting Claims */
            supporting_claims: components["schemas"]["ClaimWithContext"][];
            /** Contradicting Claims */
            contradicting_claims: components["schemas"]["ClaimWithContext"][];
            /** Revisions */
            revisions: components["schemas"]["RevisionWithTriggers"][];
        };
        /** BeliefRevision */
        BeliefRevision: {
            /** Id */
            id?: string;
            /** Belief Id */
            belief_id: string;
            /** Previous Statement */
            previous_statement: string;
            /** New Statement */
            new_statement: string;
            /** Previous Confidence */
            previous_confidence: number;
            /** New Confidence */
            new_confidence: number;
            /** Trigger Claim Ids */
            trigger_claim_ids?: string[];
            /** Revised By Agent */
            revised_by_agent: string;
            /**
             * Revised At
             * Format: date-time
             */
            revised_at?: string;
            /** Rationale */
            rationale: string;
        };
        /** Claim */
        Claim: {
            /** Id */
            id?: string;
            /** Predicate */
            predicate: string;
            /** Subject Entity Id */
            subject_entity_id: string;
            /** Object */
            object: {
                [key: string]: unknown;
            };
            /** Source Id */
            source_id: string;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at?: string;
            /** Extracted By Agent */
            extracted_by_agent: string;
            /** Raw Excerpt */
            raw_excerpt: string;
            /** @default active */
            status: components["schemas"]["ClaimStatus"];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** Superseded By Claim Id */
            superseded_by_claim_id?: string | null;
        };
        /** ClaimDetail */
        ClaimDetail: {
            claim: components["schemas"]["Claim"];
            source: components["schemas"]["Source"] | null;
            subject_entity: components["schemas"]["Entity"] | null;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "active" | "superseded" | "retracted" | "disputed";
        /**
         * ClaimWithContext
         * @description Claim joined with its source and subject entity for display.
         */
        ClaimWithContext: {
            claim: components["schemas"]["Claim"];
            source: components["schemas"]["Source"] | null;
            subject_entity: components["schemas"]["Entity"] | null;
        };
        /** Entity */
        Entity: {
            /** Id */
            id?: string;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases?: string[];
            type: components["schemas"]["EntityType"];
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at?: string;
        };
        /** EntityDetail */
        EntityDetail: {
            entity: components["schemas"]["Entity"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Relationships */
            relationships: components["schemas"]["Relationship"][];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "model" | "paper" | "benchmark" | "method" | "person" | "lab" | "repo" | "concept";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Present */
            db_present: boolean;
        };
        /** Page[Belief] */
        Page_Belief_: {
            /** Items */
            items: components["schemas"]["Belief"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Claim] */
        Page_Claim_: {
            /** Items */
            items: components["schemas"]["Claim"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Entity] */
        Page_Entity_: {
            /** Items */
            items: components["schemas"]["Entity"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceWithCount] */
        Page_SourceWithCount_: {
            /** Items */
            items: components["schemas"]["SourceWithCount"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** PipelineError */
        PipelineError: {
            /** Paper Id */
            paper_id: string;
            /** Error Type */
            error_type: string;
            /** Error Message */
            error_message: string;
        };
        /** PipelineRun */
        PipelineRun: {
            /** Id */
            id?: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Run Type
             * @default pipeline
             */
            run_type: string;
            /**
             * Papers Scouted
             * @default 0
             */
            papers_scouted: number;
            /**
             * Sources Inserted
             * @default 0
             */
            sources_inserted: number;
            /**
             * Claims Inserted
             * @default 0
             */
            claims_inserted: number;
            /**
             * Entities Created
             * @default 0
             */
            entities_created: number;
            /**
             * Beliefs Created
             * @default 0
             */
            beliefs_created: number;
            /**
             * Beliefs Revised
             * @default 0
             */
            beliefs_revised: number;
            /**
             * Avg Extraction Latency Ms
             * @default 0
             */
            avg_extraction_latency_ms: number;
            /** Errors */
            errors?: components["schemas"]["PipelineError"][];
        };
        /** Relationship */
        Relationship: {
            /** Id */
            id?: string;
            /** From Entity Id */
            from_entity_id: string;
            /** To Entity Id */
            to_entity_id: string;
            /** Type */
            type: string;
            /** Evidence Claim Ids */
            evidence_claim_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /**
         * RevisionWithTriggers
         * @description Revision joined with its trigger claims for the timeline view.
         */
        RevisionWithTriggers: {
            revision: components["schemas"]["BeliefRevision"];
            /** Trigger Claims */
            trigger_claims: components["schemas"]["Claim"][];
        };
        /**
         * SkepticActivityItem
         * @description One skeptic-triggered revision joined with its belief and trigger claims.
         *
         *     Powers the wiki's "what the skeptic challenged this week" feed. Belief
         *     lets the feed link back to the entity; trigger_claims are the counter-
         *     claims the skeptic emitted that drove the revision.
         */
        SkepticActivityItem: {
            revision: components["schemas"]["BeliefRevision"];
            belief: components["schemas"]["Belief"];
            /** Trigger Claims */
            trigger_claims: components["schemas"]["Claim"][];
        };
        /** Source */
        Source: {
            /** Id */
            id?: string;
            type: components["schemas"]["SourceType"];
            /** Url */
            url: string;
            /** Author */
            author?: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /** Raw Content Hash */
            raw_content_hash: string;
            /**
             * Reliability Prior
             * @default 0.5
             */
            reliability_prior: number;
        };
        /** SourceDetail */
        SourceDetail: {
            source: components["schemas"]["Source"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "arxiv" | "hn_post" | "hn_comment" | "github" | "twitter" | "bluesky" | "reddit" | "blog" | "leaderboard" | "agent_reasoning";
        /** SourceWithCount */
        SourceWithCount: {
            source: components["schemas"]["Source"];
            /** Claim Count */
            claim_count: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Entities */
            entities: number;
            /** Claims */
            claims: number;
            /** Beliefs */
            beliefs: number;
            /** Sources */
            sources: number;
            /** Revisions */
            revisions: number;
            /** Pipeline Runs */
            pipeline_runs: number;
            /** Last Pipeline Run At */
            last_pipeline_run_at: string | null;
            /** Last Pipeline Run Id */
            last_pipeline_run_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stats_api_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    list_runs_api_v1_pipeline_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_endpoint_api_v1_entities_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["EntityType"] | null;
                /** @description Substring match on canonical_name */
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Entity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_detail_api_v1_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_endpoint_api_v1_claims_get: {
        parameters: {
            query?: {
                predicate?: string | null;
                source_id?: string | null;
                entity_id?: string | null;
                status?: components["schemas"]["ClaimStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Claim_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_detail_api_v1_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_endpoint_api_v1_sources_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["SourceType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceWithCount_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_detail_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_beliefs_endpoint_api_v1_beliefs_get: {
        parameters: {
            query?: {
                topic?: string | null;
                currently_held?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Belief_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_detail_api_v1_beliefs__belief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                belief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliefDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_revisions_api_v1_beliefs__belief_id__revisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                belief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionWithTriggers"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_skeptic_activity_api_v1_skeptic_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkepticActivityItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
