/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top-level mesh counts
         * @description Counts of all entity types plus the most recent pipeline run timestamp. Used by the wiki home dashboard.
         */
        get: operations["stats_api_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pipeline-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent pipeline runs
         * @description Most recent pipeline runs, newest first. Defaults to 10.
         */
        get: operations["list_runs_api_v1_pipeline_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List entities
         * @description Paginated entity list with optional `type` and `q` (case-insensitive substring match on canonical_name).
         */
        get: operations["list_entities_endpoint_api_v1_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity detail
         * @description Entity record plus all claims where it is the subject and all relationships touching it (in either direction).
         */
        get: operations["entity_detail_api_v1_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List claims
         * @description Paginated claim list with filters: predicate, source_id, entity_id (subject), status. Ordered by extraction time, newest first.
         */
        get: operations["list_claims_endpoint_api_v1_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Claim detail
         * @description Claim joined with its source and subject entity for display.
         */
        get: operations["claim_detail_api_v1_claims__claim_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sources with claim counts
         * @description Paginated source list. Each row includes the number of claims extracted from that source — useful for ranking and the wiki home page.
         */
        get: operations["list_sources_endpoint_api_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source detail
         * @description Source record plus claims extracted from it (newest first).
         */
        get: operations["source_detail_api_v1_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List beliefs
         * @description Paginated belief list, ordered by most recently revised. Optional topic substring filter and currently_held boolean.
         */
        get: operations["list_beliefs_endpoint_api_v1_beliefs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Batch belief signal summaries
         * @description hype/substance score + reproduction count for the given belief ids (or all currently-held beliefs when none are given). Powers the inline signal badges on the beliefs list without an N+1 fan-out. Registered before /{belief_id} so 'signals' isn't read as an id.
         */
        get: operations["belief_signals_batch_api_v1_beliefs_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/{belief_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Belief detail with full provenance
         * @description Belief plus its supporting and contradicting claims (each joined with source and subject entity) and the full revision history. Each revision lists the claims that triggered it. This is the screenshot-worthy view: claims immutable, beliefs mutable, full provenance navigable.
         */
        get: operations["belief_detail_api_v1_beliefs__belief_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/beliefs/{belief_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revisions for a belief
         * @description Append-only revision history for a single belief, joined with the claims that triggered each revision. Ordered most-recent-first.
         */
        get: operations["belief_revisions_api_v1_beliefs__belief_id__revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skeptic/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent skeptic-triggered belief revisions
         * @description Most recent BeliefRevisions where revised_by_agent='skeptic', joined with each revision's belief and trigger claims (the counter-claims the skeptic emitted). Drives the wiki's skeptic-activity feed.
         */
        get: operations["recent_skeptic_activity_api_v1_skeptic_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/briefing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Personalized daily briefing
         * @description Loads the user's markdown profile from $MESH_PROFILE_PATH (default ~/.config/agent_mesh/profile.md), gathers candidate beliefs, revisions, and high-confidence claims for the requested date (default today), dispatches the Personalizer agent over A2A, and returns the ranked Briefing. Result is cached in-process by (date, profile_hash); edits to the profile invalidate that day's cache.
         */
        get: operations["get_briefing_api_v1_briefing_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a grounded question about a field
         * @description Answers a natural-language question using only the requested field's knowledge graph. The answer is grounded strictly in retrieved mesh rows with inline citations to beliefs/claims/entities, carries a coverage signal derived from the evidence, and returns 'uncovered' when the mesh has no relevant evidence. Read-only; nothing is persisted.
         */
        post: operations["ask_api_v1_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Operational status page
         * @description Server-rendered HTML with meta-refresh every 60s. Shows the last controller run, total row counts, LangGraph checkpoint run state (in-flight / interrupted), recent run errors, and the Langfuse 24h trace count when configured.
         */
        get: operations["status_page_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Knowledge graph nodes + edges
         * @description All entities as nodes and all relationships as edges, in the shape a client-side graph library can consume directly. ``?max_nodes`` bounds the entity count for predictable browser performance on large meshes; the most recently created entities win.
         */
        get: operations["get_graph_api_v1_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pre-aggregated graph data for the redesigned /graph view
         * @description Node + edge lists with density baked in: node ``belief_count`` drives radius, edge ``claim_count`` drives stroke width. Capped at the top 200 entities by belief count; ``total_entities`` lets the UI show a 'showing N of M' notice. Edges are only included when both endpoints survive the cap.
         */
        get: operations["get_graph_data_api_v1_graph_data_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List fields
         * @description Every field scope, each with its stored FieldProfile.
         */
        get: operations["list_fields_endpoint_api_v1_fields_get"];
        put?: never;
        /**
         * Create a field
         * @description Create a new field scope from a name + profile. The name is slugified into the immutable id/slug. A field starts with no connectors enabled — enable sources for it via the connectors endpoints.
         */
        post: operations["create_field_endpoint_api_v1_fields_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a field */
        get: operations["get_field_endpoint_api_v1_fields__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a field
         * @description Patch a field's name, profile fields, and/or active flag. slug/id are immutable. Profile edits take effect on the next pipeline run.
         */
        patch: operations["patch_field_endpoint_api_v1_fields__slug__patch"];
        trace?: never;
    };
    "/api/v1/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the connector catalog
         * @description The global catalog of source connectors a field can enable, each with its config_schema (the fields a field must supply to use it).
         */
        get: operations["list_connectors_endpoint_api_v1_connectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{slug}/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a field's connector enablement
         * @description The connectors configured for a field — enabled flag + per-field config. Join against /connectors by connector_id (== connector slug) for the catalog metadata.
         */
        get: operations["list_field_connectors_endpoint_api_v1_fields__slug__connectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fields/{slug}/connectors/{connector_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Enable/disable or reconfigure a connector for a field
         * @description Upsert one field's enablement + config of a catalog connector. The config is validated against the connector's config_schema; an unknown key, wrong type, or missing required field is a 422. Persisted on the mesh_writer role; the next pipeline run dispatches the field's enabled connectors.
         */
        put: operations["put_field_connector_api_v1_fields__slug__connectors__connector_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent roster
         * @description Per-agent aggregates for a field, busiest first: invocation count, error rate, avg latency, total tokens + cost, last-active + last run.
         */
        get: operations["get_roster_api_v1_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent-interaction graph
         * @description Cytoscape-shaped who-dispatches-whom graph: a single coordinator hub dispatches every agent. Node size = invocation volume, color = error rate; edge width = dispatch volume.
         */
        get: operations["get_agent_graph_api_v1_agents_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/invocations/{invocation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One invocation, full bounded detail
         * @description The full bounded input/output, the memory block + applied heuristic ids (resolved to their current text), model/tokens/cost, and a Langfuse deep-link to the raw prompt (when Langfuse is configured).
         */
        get: operations["get_invocation_api_v1_agents_invocations__invocation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent}/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An agent's recent invocations
         * @description Recent invocations for one agent in a field, newest first.
         */
        get: operations["get_agent_invocations_api_v1_agents__agent__invocations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * An agent's current learned memory
         * @description What this agent knows now: its active, unexpired heuristics and its recent episodic history (reconstructed from its artifacts).
         */
        get: operations["get_agent_memory_api_v1_agents__agent__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentGraph
         * @description Cytoscape-shaped agent-interaction graph for one field.
         */
        AgentGraph: {
            /** Nodes */
            nodes: components["schemas"]["AgentGraphNode"][];
            /** Edges */
            edges: components["schemas"]["AgentGraphEdge"][];
        };
        /**
         * AgentGraphEdge
         * @description A who-dispatches-whom edge; ``call_count`` drives stroke width.
         */
        AgentGraphEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Call Count
             * @default 0
             */
            call_count: number;
            /**
             * Error Count
             * @default 0
             */
            error_count: number;
        };
        /**
         * AgentGraphNode
         * @description A node in the agent-interaction graph.
         *
         *     ``role`` distinguishes the dispatching ``coordinator`` hub from the
         *     dispatched ``agent`` nodes; ``invocation_count`` drives node size and
         *     ``error_rate`` drives node color in the cytoscape view.
         */
        AgentGraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Role */
            role: string;
            /**
             * Invocation Count
             * @default 0
             */
            invocation_count: number;
            /**
             * Error Rate
             * @default 0
             */
            error_rate: number;
        };
        /** AgentHeuristic */
        AgentHeuristic: {
            /** Id */
            id?: string;
            /** Agent */
            agent: string;
            /** Skill */
            skill: string;
            /** Source */
            source?: string | null;
            /** Entity Id */
            entity_id?: string | null;
            /** Heuristic */
            heuristic: string;
            /**
             * Confidence
             * @default 0.3
             */
            confidence: number;
            /** Provenance Run Ids */
            provenance_run_ids?: string[];
            /** Provenance Claim Ids */
            provenance_claim_ids?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Last Revised At
             * Format: date-time
             */
            last_revised_at?: string;
            /**
             * Revision Count
             * @default 0
             */
            revision_count: number;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at?: string;
            /**
             * Is Currently Active
             * @default true
             */
            is_currently_active: boolean;
        };
        /**
         * AgentInvocation
         * @description One coordinator skill dispatch, captured for observability.
         *
         *     Bounded by construction: ``input_summary`` / ``output_summary`` /
         *     ``memory_block`` are capped summaries written by the coordinator — the raw
         *     prompt/output lives in Langfuse, reachable via ``trace_id``.
         */
        AgentInvocation: {
            /** Id */
            id?: string;
            /** Run Id */
            run_id: string;
            /**
             * Field Id
             * @default ai-robotics
             */
            field_id: string;
            /** Agent */
            agent: string;
            /** Skill */
            skill: string;
            /** Traceparent */
            traceparent?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Error Type */
            error_type?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Input Summary */
            input_summary?: {
                [key: string]: unknown;
            } | null;
            /** Output Summary */
            output_summary?: {
                [key: string]: unknown;
            } | null;
            /** Memory Block */
            memory_block?: string | null;
            /** Applied Heuristic Ids */
            applied_heuristic_ids?: string[];
            /** System Prefix Hash */
            system_prefix_hash?: string | null;
            /** Model */
            model?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * AgentInvocationDetail
         * @description One invocation's full bounded detail + resolved memory + Langfuse link.
         */
        AgentInvocationDetail: {
            invocation: components["schemas"]["AgentInvocation"];
            /** Applied Heuristics */
            applied_heuristics: components["schemas"]["ResolvedHeuristic"][];
            /** Langfuse Url */
            langfuse_url?: string | null;
        };
        /**
         * AgentMemory
         * @description An agent's *current* learned state: active heuristics + recent history.
         */
        AgentMemory: {
            /** Agent */
            agent: string;
            /** Heuristics */
            heuristics: components["schemas"]["AgentHeuristic"][];
            /** Episodic */
            episodic: {
                [key: string]: unknown;
            }[];
        };
        /**
         * AgentRosterEntry
         * @description Per-agent aggregate over a field's invocations — the roster row.
         */
        AgentRosterEntry: {
            /** Agent */
            agent: string;
            /**
             * Invocations
             * @default 0
             */
            invocations: number;
            /**
             * Errors
             * @default 0
             */
            errors: number;
            /**
             * Error Rate
             * @default 0
             */
            error_rate: number;
            /**
             * Avg Latency Ms
             * @default 0
             */
            avg_latency_ms: number;
            /**
             * Total Input Tokens
             * @default 0
             */
            total_input_tokens: number;
            /**
             * Total Output Tokens
             * @default 0
             */
            total_output_tokens: number;
            /**
             * Total Cost Usd
             * @default 0
             */
            total_cost_usd: number;
            /** Last Active */
            last_active?: string | null;
            /** Last Run Id */
            last_run_id?: string | null;
        };
        /**
         * Answer
         * @description A grounded, cited answer to a single field-scoped question.
         */
        Answer: {
            /** Answer Markdown */
            answer_markdown: string;
            /** Citations */
            citations?: components["schemas"]["Citation"][];
            /** @default uncovered */
            coverage: components["schemas"]["Coverage"];
            /** Caveats */
            caveats?: string[];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
        };
        /** Belief */
        Belief: {
            /** Id */
            id?: string;
            /** Topic */
            topic: string;
            /** Statement */
            statement: string;
            /** Supporting Claim Ids */
            supporting_claim_ids?: string[];
            /** Contradicting Claim Ids */
            contradicting_claim_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /**
             * Last Revised At
             * Format: date-time
             */
            last_revised_at?: string;
            /**
             * Revision Count
             * @default 0
             */
            revision_count: number;
            /**
             * Is Currently Held
             * @default true
             */
            is_currently_held: boolean;
        };
        /** BeliefDetail */
        BeliefDetail: {
            belief: components["schemas"]["Belief"];
            /** Supporting Claims */
            supporting_claims: components["schemas"]["ClaimWithContext"][];
            /** Contradicting Claims */
            contradicting_claims: components["schemas"]["ClaimWithContext"][];
            /** Revisions */
            revisions: components["schemas"]["RevisionWithTriggers"][];
            signals?: components["schemas"]["BeliefSignals"] | null;
        };
        /** BeliefRevision */
        BeliefRevision: {
            /** Id */
            id?: string;
            /** Belief Id */
            belief_id: string;
            /** Previous Statement */
            previous_statement: string;
            /** New Statement */
            new_statement: string;
            /** Previous Confidence */
            previous_confidence: number;
            /** New Confidence */
            new_confidence: number;
            /** Trigger Claim Ids */
            trigger_claim_ids?: string[];
            /** Revised By Agent */
            revised_by_agent: string;
            /**
             * Revised At
             * Format: date-time
             */
            revised_at?: string;
            /** Rationale */
            rationale: string;
        };
        /**
         * BeliefSignalSummary
         * @description Just the two signals the beliefs *list* surfaces inline per row.
         *
         *     The full BeliefSignals breakdown stays on the detail page; this keeps
         *     the list's batch lookup cheap.
         */
        BeliefSignalSummary: {
            /** Belief Id */
            belief_id: string;
            /** Hype Substance Score */
            hype_substance_score: number;
            /** Reproduction Count */
            reproduction_count: number;
        };
        /**
         * BeliefSignals
         * @description Phase 7b derived signals over a belief.
         *
         *     Pulled from the belief_hype_substance + belief_reproduction Postgres
         *     views; recomputed on read. Informational only — does not drive any
         *     mesh behavior in 7b.
         */
        BeliefSignals: {
            /** Source Type Diversity */
            source_type_diversity: number;
            /** Reproduction Count */
            reproduction_count: number;
            /** Skeptic Counter Claim Count */
            skeptic_counter_claim_count: number;
            /** Severe Failure Mode Count */
            severe_failure_mode_count: number;
            /** Claims Last 30D */
            claims_last_30d: number;
            /** Hype Substance Score */
            hype_substance_score: number;
        };
        /**
         * Briefing
         * @description The full daily digest returned by ``GET /briefing``.
         */
        Briefing: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Profile Excerpt
             * @default
             */
            profile_excerpt: string;
            /** Sections */
            sections?: components["schemas"]["BriefingSection"][];
        };
        /**
         * BriefingSection
         * @description A named group of ranked items (e.g. "New Beliefs").
         */
        BriefingSection: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Items */
            items?: components["schemas"]["PersonalizedItem"][];
        };
        /**
         * Citation
         * @description A pointer from an asserted fact to the mesh row it came from.
         *
         *     ``id`` always references a row present in the retrieved context pack — the
         *     agent drops any id the LLM invents — so the wiki can link it to an existing
         *     detail page (``/knowledge/{beliefs,claims,entities}/<id>``).
         */
        Citation: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "belief" | "claim" | "entity";
            /** Id */
            id: string;
            /**
             * Quote
             * @default
             */
            quote: string;
        };
        /** Claim */
        Claim: {
            /** Id */
            id?: string;
            /** Predicate */
            predicate: string;
            /** @default speculative */
            claim_type: components["schemas"]["ClaimType"];
            /** Subject Entity Id */
            subject_entity_id: string;
            /** Object */
            object: {
                [key: string]: unknown;
            };
            /** Source Id */
            source_id: string;
            /**
             * Extracted At
             * Format: date-time
             */
            extracted_at?: string;
            /** Extracted By Agent */
            extracted_by_agent: string;
            /** Raw Excerpt */
            raw_excerpt: string;
            /** @default active */
            status: components["schemas"]["ClaimStatus"];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
            /** Superseded By Claim Id */
            superseded_by_claim_id?: string | null;
            failure_mode?: components["schemas"]["FailureMode"] | null;
        };
        /** ClaimDetail */
        ClaimDetail: {
            claim: components["schemas"]["Claim"];
            source: components["schemas"]["Source"] | null;
            subject_entity: components["schemas"]["Entity"] | null;
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "active" | "superseded" | "retracted" | "disputed";
        /**
         * ClaimType
         * @description Phase 14a: derived classification of what a claim *asserts*, used to route
         *     synthesis (14b/c) — entity-anchored beliefs, relationship edges, or evidence
         *     signals. It is metadata derived from the predicate; it does not alter what the
         *     source said, so it does not violate claim-content immutability.
         *
         *     The taxonomy is intentionally small and 1:1 with the extractor's predicate
         *     vocabulary (see ``PREDICATE_TO_CLAIM_TYPE``):
         *
         *       score        — a benchmark/performance result ("X scores Y on Z")
         *       capability    — a property / what an entity can do ("X handles long context")
         *       comparison    — one entity vs another on an axis ("X outperforms Y on Z")
         *       attribution   — who made/owns an entity ("X developed by Y")
         *       lineage       — what an entity derives from ("X builds on Y")
         *       evaluation    — what an entity was tested on ("X evaluated on Z")
         *       reproduction  — confirms / fails to reproduce a prior result
         *       critique      — challenges the validity of a claim/result
         *       speculative   — forecast / opinion about the future
         * @enum {string}
         */
        ClaimType: "score" | "capability" | "comparison" | "attribution" | "lineage" | "evaluation" | "reproduction" | "critique" | "speculative";
        /**
         * ClaimWithContext
         * @description Claim joined with its source and subject entity for display.
         */
        ClaimWithContext: {
            claim: components["schemas"]["Claim"];
            source: components["schemas"]["Source"] | null;
            subject_entity: components["schemas"]["Entity"] | null;
        };
        /**
         * Connector
         * @description A catalog connector definition (global, reusable across fields).
         */
        Connector: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** @default builtin */
            kind: components["schemas"]["ConnectorKind"];
            /** Config Schema */
            config_schema?: {
                [key: string]: unknown;
            };
        };
        /**
         * ConnectorKind
         * @enum {string}
         */
        ConnectorKind: "builtin" | "config_driven";
        /**
         * Coverage
         * @description How well the retrieved mesh evidence supports the answer.
         *
         *     Evidence-derived (the mesh's signals), never a number the model invented.
         * @enum {string}
         */
        Coverage: "well_supported" | "thin" | "uncovered";
        /** Entity */
        Entity: {
            /** Id */
            id?: string;
            /** Canonical Name */
            canonical_name: string;
            /** Aliases */
            aliases?: string[];
            type: components["schemas"]["EntityType"];
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at?: string;
        };
        /** EntityDetail */
        EntityDetail: {
            entity: components["schemas"]["Entity"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Relationships */
            relationships: components["schemas"]["Relationship"][];
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "model" | "paper" | "benchmark" | "method" | "person" | "lab" | "repo" | "concept";
        /**
         * FailureMode
         * @description Structured taxonomy of why a Skeptic-authored counter-claim weakens
         *     or contradicts the belief it targets. Non-Skeptic claims leave this null.
         *
         *     Phase 7 pre-work. Skeptic emits one of these alongside its free-text
         *     rationale so downstream analysis (DSPy training, hype/substance score)
         *     can group failures without re-parsing English.
         * @enum {string}
         */
        FailureMode: "unsupported_extrapolation" | "cherry_picked_evidence" | "methodological_flaw" | "outdated_by_newer_claim" | "contradicted_by_source" | "definitional_ambiguity" | "other";
        /**
         * Field
         * @description A first-class field scope. Mirrors a ``knowledge.fields`` row.
         */
        Field: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            profile: components["schemas"]["FieldProfile"];
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /**
         * FieldConnector
         * @description One field's enablement + config of a catalog connector.
         */
        FieldConnector: {
            /** Field Id */
            field_id: string;
            /** Connector Id */
            connector_id: string;
            /** Config */
            config?: {
                [key: string]: unknown;
            };
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * FieldConnectorUpdate
         * @description Enable/disable + (re)configure a connector for a field.
         */
        FieldConnectorUpdate: {
            /** Config */
            config?: {
                [key: string]: unknown;
            } | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /**
         * FieldCreate
         * @description Create a field. ``name`` is slugified into the immutable id/slug; the
         *     rest seed the field's prompt-driving FieldProfile.
         */
        FieldCreate: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Entity Type Hints */
            entity_type_hints?: string[];
            /**
             * Extraction Examples
             * @default
             */
            extraction_examples: string;
            /**
             * Topic Label
             * @default sota
             */
            topic_label: string;
        };
        /**
         * FieldPatch
         * @description Patch a field's mutable attributes. All optional; slug/id never change.
         */
        FieldPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Entity Type Hints */
            entity_type_hints?: string[] | null;
            /** Extraction Examples */
            extraction_examples?: string | null;
            /** Topic Label */
            topic_label?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * FieldProfile
         * @description Prompt-driving description of a field. Serialized to ``fields.profile``.
         */
        FieldProfile: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Entity Type Hints */
            entity_type_hints?: string[];
            /**
             * Extraction Examples
             * @default
             */
            extraction_examples: string;
            /**
             * Topic Label
             * @default sota
             */
            topic_label: string;
        };
        /**
         * GraphData
         * @description Bounded graph payload. ``total_entities`` lets the UI show a
         *     "showing N of M" notice when the node list is capped.
         */
        GraphData: {
            /** Nodes */
            nodes: components["schemas"]["GraphDataNode"][];
            /** Edges */
            edges: components["schemas"]["GraphDataEdge"][];
            /** Total Entities */
            total_entities: number;
        };
        /** GraphDataEdge */
        GraphDataEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Relationship Type */
            relationship_type: string;
            /** Claim Count */
            claim_count: number;
        };
        /** GraphDataNode */
        GraphDataNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
            /** Belief Count */
            belief_count: number;
            /** Last Claim At */
            last_claim_at?: string | null;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Type */
            type: string;
            /** Confidence */
            confidence: number;
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Type */
            type: string;
        };
        /** GraphResponse */
        GraphResponse: {
            /** Nodes */
            nodes: components["schemas"]["GraphNode"][];
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db Present */
            db_present: boolean;
        };
        /** Page[Belief] */
        Page_Belief_: {
            /** Items */
            items: components["schemas"]["Belief"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Claim] */
        Page_Claim_: {
            /** Items */
            items: components["schemas"]["Claim"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[Entity] */
        Page_Entity_: {
            /** Items */
            items: components["schemas"]["Entity"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[SourceWithCount] */
        Page_SourceWithCount_: {
            /** Items */
            items: components["schemas"]["SourceWithCount"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * PersonalizedItem
         * @description One ranked candidate the user might care about.
         */
        PersonalizedItem: {
            /**
             * Item Type
             * @enum {string}
             */
            item_type: "belief" | "revision" | "claim";
            /** Item Id */
            item_id: string;
            /** Relevance Score */
            relevance_score: number;
            /** Rationale */
            rationale: string;
        };
        /** PipelineError */
        PipelineError: {
            /** Paper Id */
            paper_id: string;
            /** Error Type */
            error_type: string;
            /** Error Message */
            error_message: string;
        };
        /** PipelineRun */
        PipelineRun: {
            /** Id */
            id?: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Run Type
             * @default controller
             */
            run_type: string;
            /**
             * Triggered By
             * @default manual
             */
            triggered_by: string;
            /**
             * Papers Scouted
             * @default 0
             */
            papers_scouted: number;
            /**
             * Sources Inserted
             * @default 0
             */
            sources_inserted: number;
            /**
             * Claims Inserted
             * @default 0
             */
            claims_inserted: number;
            /**
             * Entities Created
             * @default 0
             */
            entities_created: number;
            /**
             * Beliefs Created
             * @default 0
             */
            beliefs_created: number;
            /**
             * Beliefs Revised
             * @default 0
             */
            beliefs_revised: number;
            /**
             * Avg Extraction Latency Ms
             * @default 0
             */
            avg_extraction_latency_ms: number;
            /** Errors */
            errors?: components["schemas"]["PipelineError"][];
        };
        /** Relationship */
        Relationship: {
            /** Id */
            id?: string;
            /** From Entity Id */
            from_entity_id: string;
            /** To Entity Id */
            to_entity_id: string;
            /** Type */
            type: string;
            /** Evidence Claim Ids */
            evidence_claim_ids?: string[];
            /**
             * Confidence
             * @default 0.5
             */
            confidence: number;
        };
        /**
         * ResolvedHeuristic
         * @description An applied heuristic id resolved to its text (for the invocation view).
         */
        ResolvedHeuristic: {
            /** Id */
            id: string;
            /** Heuristic */
            heuristic: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * RevisionWithTriggers
         * @description Revision joined with its trigger claims for the timeline view.
         */
        RevisionWithTriggers: {
            revision: components["schemas"]["BeliefRevision"];
            /** Trigger Claims */
            trigger_claims: components["schemas"]["Claim"][];
        };
        /**
         * SkepticActivityItem
         * @description One skeptic-triggered revision joined with its belief and trigger claims.
         *
         *     Powers the wiki's "what the skeptic challenged this week" feed. Belief
         *     lets the feed link back to the entity; trigger_claims are the counter-
         *     claims the skeptic emitted that drove the revision.
         */
        SkepticActivityItem: {
            revision: components["schemas"]["BeliefRevision"];
            belief: components["schemas"]["Belief"];
            /** Trigger Claims */
            trigger_claims: components["schemas"]["Claim"][];
        };
        /** Source */
        Source: {
            /** Id */
            id?: string;
            type: components["schemas"]["SourceType"];
            /** Url */
            url: string;
            /** Author */
            author?: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at?: string;
            /** Raw Content Hash */
            raw_content_hash: string;
            /**
             * Reliability Prior
             * @default 0.5
             */
            reliability_prior: number;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** SourceDetail */
        SourceDetail: {
            source: components["schemas"]["Source"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
        };
        /**
         * SourceType
         * @enum {string}
         */
        SourceType: "arxiv" | "hn_post" | "hn_comment" | "github" | "twitter" | "bluesky" | "reddit" | "blog" | "leaderboard" | "web" | "rss" | "rest" | "agent_reasoning";
        /** SourceWithCount */
        SourceWithCount: {
            source: components["schemas"]["Source"];
            /** Claim Count */
            claim_count: number;
        };
        /** StatsResponse */
        StatsResponse: {
            /** Entities */
            entities: number;
            /** Claims */
            claims: number;
            /** Beliefs */
            beliefs: number;
            /** Sources */
            sources: number;
            /** Revisions */
            revisions: number;
            /** Pipeline Runs */
            pipeline_runs: number;
            /** Last Pipeline Run At */
            last_pipeline_run_at: string | null;
            /** Last Pipeline Run Id */
            last_pipeline_run_id: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    stats_api_v1_stats_get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_pipeline_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_endpoint_api_v1_entities_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["EntityType"] | null;
                /** @description Substring match on canonical_name */
                q?: string | null;
                limit?: number;
                offset?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Entity_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_detail_api_v1_entities__entity_id__get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_claims_endpoint_api_v1_claims_get: {
        parameters: {
            query?: {
                predicate?: string | null;
                source_id?: string | null;
                entity_id?: string | null;
                status?: components["schemas"]["ClaimStatus"] | null;
                limit?: number;
                offset?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Claim_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    claim_detail_api_v1_claims__claim_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_endpoint_api_v1_sources_get: {
        parameters: {
            query?: {
                type?: components["schemas"]["SourceType"] | null;
                limit?: number;
                offset?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SourceWithCount_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_detail_api_v1_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_beliefs_endpoint_api_v1_beliefs_get: {
        parameters: {
            query?: {
                topic?: string | null;
                currently_held?: boolean | null;
                limit?: number;
                offset?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Belief_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_signals_batch_api_v1_beliefs_signals_get: {
        parameters: {
            query?: {
                ids?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliefSignalSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_detail_api_v1_beliefs__belief_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                belief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeliefDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    belief_revisions_api_v1_beliefs__belief_id__revisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                belief_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevisionWithTriggers"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_skeptic_activity_api_v1_skeptic_recent_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkepticActivityItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_briefing_api_v1_briefing_get: {
        parameters: {
            query?: {
                date?: string | null;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Briefing"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_v1_ask_post: {
        parameters: {
            query?: {
                /** @description Field slug to scope the answer to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Answer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_page_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
        };
    };
    get_graph_api_v1_graph_get: {
        parameters: {
            query?: {
                max_nodes?: number;
                max_edges?: number;
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_data_api_v1_graph_data_get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fields_endpoint_api_v1_fields_get: {
        parameters: {
            query?: {
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Field"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_field_endpoint_api_v1_fields_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Field"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_field_endpoint_api_v1_fields__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Field"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_field_endpoint_api_v1_fields__slug__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Field"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connectors_endpoint_api_v1_connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connector"][];
                };
            };
        };
    };
    list_field_connectors_endpoint_api_v1_fields__slug__connectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConnector"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_field_connector_api_v1_fields__slug__connectors__connector_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                connector_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldConnectorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldConnector"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roster_api_v1_agents_get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRosterEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_graph_api_v1_agents_graph_get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentGraph"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invocation_api_v1_agents_invocations__invocation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invocation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInvocationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_invocations_api_v1_agents__agent__invocations_get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
                limit?: number;
            };
            header?: never;
            path: {
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentInvocation"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_memory_api_v1_agents__agent__memory_get: {
        parameters: {
            query?: {
                /** @description Field slug to scope results to */
                field?: string;
                limit?: number;
            };
            header?: never;
            path: {
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMemory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
