"""Field Overview — the "state of the field" read surface.

One GET composes everything the Overview page renders: the latest LLM-written
narrative brief (generated by the controller's ``write-field-brief`` skill on
its maintenance cooldown), the strongest held beliefs, movement inside the
window, contested beliefs, and open discovery gaps. Read-only, field-generic,
and intentionally *not* admin-gated — this is the public face of a field.
"""
from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, HTTPException
from mesh_db.field_briefs import get_latest_field_brief
from mesh_db.fields import get_field_by_slug
from mesh_db.overview import (
    contested_beliefs,
    movement_stats,
    open_gaps,
    recently_revised_beliefs,
    strongest_beliefs,
)
from mesh_models.belief import Belief
from pydantic import BaseModel

from mesh_api.deps import ConnDep

router = APIRouter(prefix="/api/v1/fields", tags=["overview"])


class OverviewBelief(BaseModel):
    id: str
    topic: str
    statement: str
    confidence: float
    contradiction_count: int = 0
    last_revised_at: datetime


class OverviewGap(BaseModel):
    id: str
    question: str
    rationale: str = ""
    status: str


class MovementStats(BaseModel):
    held_total: int
    new: int
    revised: int
    dropped: int
    window_days: int


class FieldBriefOut(BaseModel):
    narrative: str
    model: str = ""
    generated_at: datetime


class FieldOverviewResponse(BaseModel):
    field: str
    brief: FieldBriefOut | None = None
    movement: MovementStats
    strongest: list[OverviewBelief]
    recently_revised: list[OverviewBelief]
    contested: list[OverviewBelief]
    gaps: list[OverviewGap]


def _belief_out(b: Belief) -> OverviewBelief:
    return OverviewBelief(
        id=b.id,
        topic=b.topic,
        statement=b.statement,
        confidence=b.confidence,
        contradiction_count=len(b.contradicting_claim_ids),
        last_revised_at=b.last_revised_at,
    )


@router.get(
    "/{slug}/overview",
    response_model=FieldOverviewResponse,
    summary="State-of-the-field overview",
    description=(
        "The latest narrative brief plus strongest / recently-revised / "
        "contested beliefs, movement counts, and open discovery gaps."
    ),
)
def field_overview_endpoint(slug: str, conn: ConnDep) -> FieldOverviewResponse:
    fld = get_field_by_slug(conn, slug)
    if fld is None:
        raise HTTPException(status_code=404, detail=f"Unknown field: {slug}")
    field_id = fld.id

    brief = get_latest_field_brief(conn, field_id)
    return FieldOverviewResponse(
        field=slug,
        brief=(
            FieldBriefOut(
                narrative=brief.narrative,
                model=brief.model,
                generated_at=brief.generated_at,
            )
            if brief is not None
            else None
        ),
        movement=MovementStats(**movement_stats(conn, field_id)),
        strongest=[_belief_out(b) for b in strongest_beliefs(conn, field_id, limit=8)],
        recently_revised=[
            _belief_out(b)
            for b in recently_revised_beliefs(conn, field_id, limit=5)
        ],
        contested=[_belief_out(b) for b in contested_beliefs(conn, field_id, limit=5)],
        gaps=[
            OverviewGap(
                id=g.id,
                question=g.question,
                rationale=g.trigger_rationale or "",
                status=g.status.value,
            )
            for g in open_gaps(conn, field_id, limit=5)
        ],
    )
